---
name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:

  build:
    name: Build the lib with Idris2 HEAD
    runs-on: ubuntu-latest
    env:
      PACK_DIR: /root/.pack
    strategy:
      fail-fast: false
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install --yes lld
      - name: Install bcrypt
        run: pack --no-prompt install bcrypt
      - name: Build bcrypt
        run: pack typecheck bcrypt
      - name: Test bcrypt
        run: pack --no-prompt test bcrypt
